# i.MX Platform Support
snd-soc-imx-objs := imx-pcm.o
snd-soc-imx-ssi-objs := imx-ssi.o
snd-soc-imx-esai-objs := imx-esai.o

obj-$(CONFIG_SND_MXC_SOC) += snd-soc-imx.o
obj-$(CONFIG_SND_MXC_SOC_SSI) += snd-soc-imx-ssi.o
obj-$(CONFIG_SND_MXC_SOC_ESAI) += snd-soc-imx-esai.o

# Support record from playback
snd-soc-imx-record-from-playback-objs := imx_pcm_dev.o
obj-$(CONFIG_SND_MXC_SOC_RECORD_FROM_PLAYBACK) += snd-soc-imx-record-from-playback.o

# i.MX Machine Support
snd-soc-imx-3stack-wm8350-objs := imx-3stack-wm8350.o
obj-$(CONFIG_SND_SOC_IMX_3STACK_WM8350) += snd-soc-imx-3stack-wm8350.o
snd-soc-imx-3stack-ak4647-objs := imx-3stack-ak4647.o
obj-$(CONFIG_SND_SOC_IMX_3STACK_AK4647) += snd-soc-imx-3stack-ak4647.o
snd-soc-imx-3stack-wm8580-objs := imx-3stack-wm8580.o
obj-$(CONFIG_SND_SOC_IMX_3STACK_WM8580) += snd-soc-imx-3stack-wm8580.o
snd-soc-imx-3stack-wm8903-objs := imx-3stack-wm8903.o
obj-$(CONFIG_SND_SOC_IMX_3STACK_WM8903) += snd-soc-imx-3stack-wm8903.o
snd-soc-imx-apollo-wm1808-objs := imx-apollo-wm1808.o
obj-$(CONFIG_SND_SOC_IMX_APOLLO_WM1808) += snd-soc-imx-apollo-wm1808.o
snd-soc-imx-bigbang-as3543-objs := imx-bigbang-as3543.o
obj-$(CONFIG_SND_SOC_IMX_BIGBANG_AS3543) += snd-soc-imx-bigbang-as3543.o